Yooooomi/your_spotify

- client/public/.htaccess
This is needed for proper Apache support out-of-the-box.
> Create .htaccess to be copied to build

- README.md
It looks like Spotify now allows extended data downloads through https://www.spotify.com/us/account/privacy/, so I updated this accordingly.
> Clear up input methods

- client/src/scenes/Settings/Importer/FullPrivacy/FullPrivacy.tsx
Change localized link: https://www.spotify.com/fr/account/privacy/
To the generic: https://www.spotify.com/account/privacy/
Currently, this link redirects me to the French version of the site, but I am in the US.  The new link should dynamically redirect users to their localized version of the site.
> Update FullPrivacy.tsx to remove /fr/ from link

- server/src/bin/www.ts
This PR addresses issue #275, which had been closed without a definitive resolution. The solution proposed by this pull request is a straightforward one, without any complicated retry mechanisms. As elaborated in the [commit description](https://github.com/Yooooomi/your_spotify/pull/297/commits/dead24f07a9df5a2630fb4a0fd55783fe0d36498), this patch ensures that unrecoverable errors thrown within `dbLoop()` do not get "swallowed" by the `catch()` in `src/bin/www.ts`. Consequently, it prevents the server from entering an idle state where it continues to run without importing any recently played songs, a scenario that will result in unexpected data loss.
I remain committed to seeing this issue through to resolution. Although my previous comments in the issue may have come across as …
> Exit on unrecoverable errors in `dbLoop`

- server/src/routes/index.ts
Initially there is always only one Admin user after setting the application up. As consequence `users.length <=1`will always be true and the API endpoints responds with the error code 400 upon trying to add an additional admin user.
This fix adds a validation which checks if an admin user is removed or added.  
The error response will only be sent upon removal.
> Fix admin user api endpoint

- apps/server/src/database/queries/stats.ts
- apps/server/src/database/queries/statsTools.ts
While requests are performant for many use cases, I have around 225000 listened songs (23000 different) with Your Spotify hosted on a Raspberry PI, so navigate on the client takes a lot of time, especially with the "Last year" or "All" timeframe.
This PR improves performances of `getBestSongsNbOffseted`, `getBestArtistsNbOffseted` and `getBestAlbumsNbOffseted` by a factor of ~10. My approach was to group all `Infos` of the same track at start. This avoids to compute many times the same `Info`, which helps a lot for the `lightTrackLookupPipeline`.
*done on mac m1, not on the Raspberry*
A request for the top songs with date range "All" before this PR takes in my case `11,8s`:
```
server  | GET /spotify/top/songs?start=2017-11-18T12:18:39.000Z&end=2024-02-26T14:07:27.570Z&nb=20&offset=0 200 …
```
> Improve Songs/Artists/Albums query performances by ~50

- apps/client/src/components/ButtonsHeader/ButtonsHeader.tsx
- apps/client/src/components/ButtonsHeader/index.module.css
- apps/client/src/components/ChartCard/index.module.css
- apps/client/src/components/Header/index.module.css
- apps/client/src/components/TitleCard/index.module.css
- apps/client/src/index.css
- apps/client/src/services/theme.ts
- Improve background contrast with the cards
- Remove the blocks before titles (they seem to be too much now that the cards are well defined)
- And remove header background for a more modern look
Since design changes can be controversial I'm very open to 'request changes', and you can close it if you don't like it
> design: Remove header background

- apps/client/src/App.tsx
- apps/client/src/scenes/Benchmarks/Benchmarks.tsx
- apps/client/src/scenes/Benchmarks/index.ts
- apps/server/src/database/queries/album.ts
- apps/server/src/database/queries/artist.ts
- apps/server/src/database/queries/stats.ts
- apps/server/src/database/queries/statsTools.ts
- apps/server/src/database/queries/track.ts
- apps/server/src/routes/album.ts
- apps/server/src/routes/artist.ts
- apps/server/src/routes/spotify.ts
- apps/server/src/routes/track.ts
- Improve some requests performances (ranking, artists, tracks, albums, listening time...)
- Adds a new hidden page to test the requests
Benchmarks: https://github.com/Yooooomi/your_spotify/pull/354#issuecomment-1973566720
> Improve global request performances

- apps/server/src/routes/oauth.ts
The `COOKIE_VALIDITY_MS` environment variable is supposed to configure how long issued session cookies are valid for. However, before this commit, this setting was only respected when the `OFFLINE_DEV_ID` setting (which seems to be used for local testing during development) is enabled.
This commit changes this so the configured validity period also gets applied to session cookies issued using the Spotify login OAuth flow.
> Respect COOKIE_VALIDITY_MS setting in production

- apps/client/src/components/Layout/Sider/SiderCategory/index.module.css
- apps/client/src/components/Layout/Sider/index.module.css
- apps/client/src/components/SiderSearch/index.module.css
- apps/client/src/index.css
Some design refinements for the drawer
| Before | After |
| --- | --- |
| <img width="248" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/d6d5914a-5d8f-4654-8f8f-6f695bb8b95b"> | <img width="248" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/266001ea-d1b3-41ae-b6c6-48e1c8d03cee"> |
| Before | After |
| --- | --- |
| <img width="248" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/47bd2b57-7885-4d02-8a63-950b8d0a3882"> | <img width="248" alt="image" src="https://github.com/Yooooomi/your_spotify/assets/12123721/d414d428-c14e-4ca0-8c99-d6904cbde016"> |
> feat: rework sider design

- apps/client/public/index.html
Fixing a problem with inaccessible manifest file when using HTTP basic auth.
I am using nginx + basic auth for `your_spotify` frontend.
After the last update, I can no longer see the left sidebar in Chrome. In Safari it works fine.
So on chrome page looks like that (artist and song information are hidden by me):
After a little investigation I found that `manifest.json` cannot be loaded, and the problem is that it does not use auth headers when making the request:
The situation is described here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin#example_web_manifest_with_credentials
Thus, this PR fixes this problem.
> Set `use-credentials` for manifest file

- docker-compose-example.yml
After a server restart, only containers which are restart: always (or unless-stopped) will start on startup!
> Make sure Mongo restarts

- apps/client/src/services/stats.ts
The `getPercentMore` function had an issue in calculating percentage decreases when `now` was less than `old`.
> Fix calculation of negative percentages in `getPercentMore`

- apps/server/src/tools/importers/full_privacy.ts
Spotify seems to have changed their extended streaming history export format. This PR updates the validation schema to match the new format.
Fixes #452
Solution described in https://github.com/Yooooomi/your_spotify/issues/452#issuecomment-2495558181
- Updated `fullPrivacyFileSchema` to match Spotify's new export format:
- Removed `username` field (no longer provided)
- Removed `user_agent_decrypted` field (no longer provided)
- Renamed `ip_addr_decrypted` to `ip_addr` to match new field name
> fix: update Spotify extended streaming history schema to match new format

- .github/workflows/nightly.yml
- .github/workflows/release.yml
This PR sets some OpenContainer labels of the docker images published to DockerHub.
I implemented this as I want Renovate to [parse Changelogs correctly](https://docs.renovatebot.com/modules/datasource/docker/#table-of-values). It infers the GitHub repo using the standardized label `org.opencontainers.image.source`.
Since it wasn't set yet, Renovate failed to fetch said changelog.
This solution (should) not only add this `image.source` label but also [other best-practice labels](https://github.com/marketplace/actions/docker-metadata-action#bake-definition)
> fix(ci): set opencontainer labels of docker images

- apps/client/scripts/build/10-build_react.sh
- apps/client/scripts/run/run.sh
- apps/client/scripts/run/run_dev.sh
- apps/client/scripts/run/serve.sh
- apps/client/scripts/run/variables.sh
- apps/server/scripts/run/run.sh
- apps/server/scripts/run/run_dev.sh
Hey! This project is a lot of fun, but I've noticed that the Docker containers are slow to terminate. When I stop them, the containers keep running up until Docker decides to kill them. This is due to the shell scripts being run as PID 0, and not passing signals to node.
This PR changes the startup scripts to use `exec`, which replaces the script PID with the command it runs. This means when Docker sends a `SIGTERM`, it will go directly to node, immediately telling it to exit.
I also went ahead and added `set -e` which makes a script exit if a command fails. This removes the need for chaining `&&`.
> Fix slow Docker container termination

- apps/client/src/components/IdealImage/IdealImage.tsx
- apps/client/src/components/IdealImage/index.module.css
- apps/client/src/components/PlayButton/index.module.css
- apps/client/src/scenes/AlbumStats/index.module.css
- apps/client/src/scenes/ArtistStats/FirstAndLast/index.module.css
- apps/client/src/scenes/ArtistStats/index.module.css
- apps/client/src/scenes/Tops/Albums/Album/index.module.css
- apps/client/src/scenes/TrackStats/index.module.css
For videos, the spotify api can return song covers that are not square, the default behavior was to distort the images.
We could also get the cover on the audio only version of the song, but this may require an additional api call.
> fix(client): zoom cover images instead of stretching

- apps/client/package.json
- apps/server/package.json
- package.json
The version in the `package.json` files wasn't updated with the 1.13.0 release, and thus the UI still displays the old version.
> bump to 1.13.0

- .github/workflows/release.yml
I'm glad you added ghcr repos in the latest release, but during migration I noticed the client hadn't gotten the release tag pushed. I took a look at the CI script and there's a typo causing the client to be pushed to to the server ghcr repo. This PR fixes that.
Related to #510
> ci: fix client ghcr repo not being pushed to on release

- apps/client/src/components/History/Track/Track.tsx
- apps/client/src/scenes/AlbumStats/AlbumStats.tsx
- apps/client/src/scenes/Tops/Albums/Album/Album.tsx
- apps/client/src/scenes/Tops/Artists/Artist/Artist.tsx
- apps/client/src/scenes/Tops/Songs/Track/Track.tsx
- apps/client/src/services/stats.ts
Before:
After:
The percentage now wraps to the next line. Imo that's fine though as the line height is as large as it is now anyway due to the thumbnail.
> Format hrs:mins durations nicely

- apps/client/src/services/intervals.ts
This PR adds a predefined "Today" interval to intervals.ts, allowing users to filter and analyze their Spotify activity specifically for the current calendar day, rather than just the last 24 hours. This improves usability for daily insights.
> feat: Add preset interval for today in intervals.ts

- apps/server/src/routes/spotify.ts
This update introduces a helper function normalizeOtherIdsQuery to handle query parameters where otherIds[] may be passed as either a single value or an array. This ensures consistent handling before validation and prevents potential issues when interacting with the collaborativeSchema.
This should fix #524.
This normalization has been applied to the following routes:
/collaborative/top/songs
/collaborative/top/artists
/collaborative/top/genres
📝 Note:
This is my first time working on a large-scale project like this, and I'm not yet very familiar with TypeScript or Node.js. Feedback and suggestions for improvement are very welcome!
> Fix: collaborative routes: normalize otherIds query param

- apps/server/src/app.ts
Mask query parameters such as the OAuth code in HTTP logs produced by
the API server.
> Mask sensitive query parameters in HTTP logs
